# Generated by Django 3.2.25 on 2026-03-22 12:25

from django.db import migrations, models
import django.db.models.deletion
import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0210_auto_20260322_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemClarificationTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], max_length=7, verbose_name='language')),
                ('description', models.TextField(validators=[judge.models.problem.disallowed_characters_validator], verbose_name='translated clarification body')),
                ('clarification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='judge.problemclarification', verbose_name='clarification')),
            ],
            options={
                'verbose_name': 'clarification translation',
                'verbose_name_plural': 'clarification translations',
                'unique_together': {('clarification', 'language')},
            },
        ),
    ]
