# Generated by Django 3.2.25 on 2026-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0211_auto_20260322_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionsource',
            name='source',
            field=models.TextField(max_length=1048576, verbose_name='source code'),
        ),
    ]
