# Generated by Django 3.2.25 on 2026-07-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0215_contest_format_voi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='site_theme',
            field=models.CharField(choices=[('auto', 'Follow system default'), ('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10, verbose_name='site theme'),
        ),
    ]
